#!/bin/sh

remote=`git remote | head -n 1`

docker build \
  --build-arg VCS_REF=`git rev-parse --short HEAD` \
  --build-arg VCS_URL=`git config --get "remote.$remote.url"` \
  --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
  -t $IMAGE_NAME .
